# TODO: Remove in future and in IDE for other profiles
spring.profiles.active=local
spring.application.name=lernello
# Multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
# JWT: Expiration in milliseconds (7 days)
jwt.expiration=604800000
# File-Storage-Path
# TODO remove file storage path in future
storage.path=./data/files
