# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:15432/lernello
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=secret
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Mail
spring.mail.host=mail.infomaniak.ch
spring.mail.port=587
spring.mail.username=info@lernello.ch
spring.mail.password=CHANGE_ME
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# CORS
cors.allowed-origins=http://localhost:5173,http://localhost:5174
# JWT Secret
jwt.secret=changemeeeeeeeeeeeeeeeeeeeeeeeee
# Password Reset URL
app.reset-password-url=http://localhost:5173/reset-password
